---
# Thx to K'Walla for the suggestion!
#
# This is a collection of monitors to check various states at regular scheduled intervals.
# Monitors performed:
#  Check for disk space used (Default setting is once a day)

# Settings to edit:
# All "diskcheck_" entries

- name: Install Monitor
  hosts: all
  vars:
    diskcheck_minute: '0' # Checks every day
    diskcheck_hour: '*'
    diskcheck_day: '*'
    diskcheck_month: '*'
    diskcheck_weekday: '*'
  gather_facts: no

  tasks:
    - name: Clone OT-NodeWatch git repository
      git:
        repo: 'https://github.com/calr0x/OT-NodeWatch.git'
        dest: /root/OT-NodeWatch
        force: yes

    - name: Install config.sh
      copy:
        src: /root/OT-NodeWatch/config.sh
        dest: /root/OT-NodeWatch/config.sh
        owner: root
        group: root
        mode: '0600'

    - name: Install disk_space.sh
      copy:
        src: /root/OT-NodeWatch/disk_check/disk_check.sh
        dest: /root/OT-NodeWatch/disk_check/disk_check.sh
        owner: root
        group: root
        
    - name: Delete existing monitor (docker check) schedule from cron
      cron:
        name: Monitor Disk Check
        state: absent

    - name: Add monitor (disk check) schedule to cron (once a day)
      cron:
        name: Monitor Disk Check
        minute: "{{ diskcheck_minute }}"
        hour: "{{ diskcheck_hour }}"
        day: "{{ diskcheck_day }}"
        month: "{{ diskcheck_month }}"
        weekday: "{{ diskcheck_weekday }}"
        job: "/root/OT-NodeWatch/disk_check/disk_check.sh"
