---

# This is a collection of monitors to check various states at regular scheduled intervals.
# Monitors performed:
#  Check for bids last 15 minutes
#  Check docker container "otnode" is running every 5 minutes

# Settings to edit:
# All "bidcheck_" entries
# All "dockercheck_" entries

####################################################################
# This script will:
# 1. Delete existing OT-NodeWatch directory
# 2. Clone git.
# 3. Copy edited config.
# 4. Delete any existing cron jobs for bid_watch/docker_watch.
# 5. Add cron jobs for both with current configured values.
# 6. Stop Cosmic_Overlay ping script if running.

- name: Install Monitors
  hosts: all
  vars_files: "/root/OT-Ansible-Files-and-Playbooks/config-otnode-ansible.yml"
  gather_facts: no

  tasks:
    - name: Delete existing OT-NodeWatch folder
      file:
        path: /root/OT-NodeWatch
        state: absent

    - name: Delete existing OT-Settings folder
      file:
        path: /root/OT-Settings
        state: absent

    - name: Installing jq
      apt:
        name: jq
        state: present
        update_cache: yes

    - name: Clone OT-NodeWatch git repository
      git:
        repo: 'https://github.com/calr0x/OT-NodeWatch.git'
        dest: /root/OT-NodeWatch
        force: yes

    - name: Clone OT-Settings git repository
      git:
        repo: 'https://github.com/calr0x/OT-Settings.git'
        dest: /root/OT-Settings
        force: yes

    - name: Install config.sh
      copy:
        src: ~/OT-Settings/config.sh
        dest: /root/OT-Settings/config.sh
        owner: root
        group: root
        mode: '0600'

    - name: Delete existing monitor (bid check) schedule from cron
      cron:
        name: Monitor Bid Check
        state: absent

    - name: Add monitor (bid check) schedule to cron (every hour)
      cron:
        name: Monitor Bid Check
        minute: "{{ bid_check_minute }}"
        hour: "{{ bid_check_hour }}"
        day: "{{ bid_check_day }}"
        month: "{{ bid_check_month }}"
        weekday: "{{ bid_check_weekday }}"
        job: "/root/OT-NodeWatch/bid_check/bid_check.sh"

